services:
    locastic.component.oib_validator.utils.oib_content_checker:
        class: Locastic\Component\OibValidator\Utils\OibContentChecker

    locastic.component.oib_validator.validator.constraints.oib_validator:
        class: Locastic\Component\OibValidator\Validator\Constraints\OibValidator
        arguments:
            - '@locastic.component.oib_validator.utils.oib_content_checker'
        tags:
            - { name: validator.constraint_validator }
